### PR TITLE
using distributable_post_types filter on the pull UI

### LINKED ISSUE #720: distributable_post_types filter is not respected in Pull UI screen
**Describe the bug**
while filtering the permited post types via `distributable_post_types`, I noticed that the dropdown in de Pull UI has all the post types in the dropdown. 

**Steps to Reproduce**
Filter the permited post types:

```
add_filter( 'distributable_post_types', function() {
    return [ 'post' => 'post' ];
});
```

Go to the Pull overview page en check the dropdown.

**Expected behavior**
I expected only the Post post type in the dropdown.

**Environment information**
 - WordPress version: 5.6.1

Version | 1.6.2

Override Author Byline: Yes

Media Handling: Featured image and attached images

Internal Connections | 
Maas Wijkontwikkeling:  - Blog ID: 2 - URL: https://waal.local/maasontwikkel - Registered: 2021-02-01 13:52:41 - Last updated: 2021-02-13 17:09:18
Woonslim:  - Blog ID: 3 - URL: https://waal.local/woonslim - Registered: 2021-02-01 13:52:56 - Last updated: 2021-02-03 08:33:12

External Connections | N/A

**Additional context**
Thank you!

### PR DESCRIPTION
**Pull request by dhanendran**
### Description of the Change
Using the `distributable_post_types` filter on the pull UI.

Closes https://github.com/10up/distributor/issues/720

### Verification Process
- Whitelist set of post types in site one
- Try to add new post types to that list on the pull UI using `dt_available_pull_post_types` filter
- We should see the post types that are whitelisted as distributable that are present in the `dt_available_pull_post_types` filter should be displayed

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/10up/.github/blob/trunk/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

Added: New filter `dt_available_push_post_types` is available to filter the post types that are available to push.

### Credits
Props @dhanendran, @jmslbam, @dkotter

### CODE REVIEW

**Comment by peterwilsoncc** [comment]
Thanks for the pull request @dhanendran. 

In the discussion on #720, there was the suggestion to introduce the filter `dt_available_push_post_types` to match the existing `dt_available_pull_post_types` filter.

Do you have the bandwidth to add that to this pull request or would you like me to work on it?

**Comment by dhanendran** [comment]
@peterwilsoncc I will work on it this week.

**Comment by dhanendran** [comment]
@peterwilsoncc I have added the new filter now.

File: includes/utils.php [hunk 1]
```diff
@@ -295,17 +310,30 @@ function distributable_post_types() {
...
+	 *
+	 * Helpful for sites that want to push custom post type content to another site.
+	 *
+	 * @hook dt_available_push_post_types
+	 *
+	 * @param {array} Post types that are distributable. Default all post types except `dt_ext_connection` and `dt_subscription`.
+	 *
+	 * @return {array} Post types available for push.
+	 */
+	$push_post_types = apply_filters( 'dt_available_push_post_types', array_diff( $post_types, [ 'dt_ext_connection', 'dt_subscription' ] ) );
```
Comment (peterwilsoncc) [inline includes/utils.php]: I think this will need to go in the `syndicate()` function used for the push-ui.

https://github.com/10up/distributor/blob/061383441a8b0dbc21a3b5fc4d2bf0063a14349a/includes/push-ui.php#L38

The final check within `syndicate()` checks the post types, so the new filter can be set up there.

Comment (dhanendran) [reply includes/utils.php]: @peterwilsoncc `distributable_post_types` function is used in multiple places, so if we are adding this in `syndicatable()` function then other places won't get the right data.

Comment (peterwilsoncc) [reply includes/utils.php]: The goal is that `distributable_post_types` be generic and apply to both pushing and pulling of posts. `dt_available_push_post_types` and `dt_available_pull_post_types` should only apply to a single direction.

Moving the `dt_available_push_post_types` filter to the `syndicate()` function will ensure it only applies in one direction.

Comment (dhanendran) [reply includes/utils.php]: @peterwilsoncc that makes sense. I have moved that filter now.

File: includes/utils.php [hunk 2]
```diff
@@ -245,21 +245,25 @@ function set_meta( $post_id, $meta ) {
...
-					'name' => 'external' === $type ? $post_type['name'] : $post_type->label,
-					'slug' => 'external' === $type ? $post_type['slug'] : $post_type->name,
-				);
-			}
+	$post_types               = array();
+	$local_post_types         = array();
+	$remote_post_types        = $connection->get_post_types();
+	$distributable_post_types = distributable_post_types();
+
+	// Return empty array, if the source site is not distributing any post type.
```
Comment (peterwilsoncc) [inline includes/utils.php:253]: Something to be aware of with the change to the early `return` pattern.

In the current version of the plugin, an empty array would still be passed to `dt_available_pull_post_types` for developers to modify as they wish. With this change, the empty array is no longer passed through the filter.

I think it will be fine though.

**Review by peterwilsoncc — APPROVED** [review]
Thanks @dhanendran , this looks good to me.
