### PR TITLE
Tweak: create pot file with WP CLI and  move translations to JS files

### LINKED ISSUE #267: Do internationalization properly
Coming out of #266, let's do internationalization properly! These are probably worth breaking out into sub-issues:

- [x]  Fix up the way strings are internationalized generally (I see a bunch of English-centric assumptions that don't actually work such as appending an `s` to pluralize)
- [x] Do everything correctly to get things registered in PHP and JS
- [ ] Add JS PO file generation to the build process
- [ ] Lay out a plan for how we source and include translations

### LINKED ISSUE #660: i18n po/mo not loaded
**Describe the bug**
I translated Distributor in french but only strings in the plugin page but the translations are not loaded in the plugin setings it self:
distrubor-fr
distrubor-fr-settings

[distributor-fr_FR.zip](https://github.com/10up/distributor/files/5432900/distributor-fr_FR.zip)

**Environment information**
 - WordPress version: 5.5.1

### LINKED ISSUE #947: Translation files do not include JavaScript strings.
### Describe the bug

The node command currently used by Distributor does not scan JavaScript files for translation strings. As a result, the .pot file generated during the build process is missing strings.

WP CLI is able to scan both PHP and JavaScript files when generating pot files. To ensure the compressed files are included in the build process, the WP-CLI command required is:

```sh
wp i18n make-pot . --include="distributor.php,dist/js/*.min.js,includes,templates,assets"
```

The `wp i18n make-pot` command requires PHP but does not require WordPress be installed. Switching to the command should be relatively straightforward using [the `shivammathur/setup-php` action](https://github.com/marketplace/actions/setup-php-action).

Props @ravinderk for bringing this to my attention.

### Steps to Reproduce

1. Checkout the `develop` branch of this repo
2. Run `npm i; npm run build; npm run makepot`
3. In a text editor open the generated pot file in the `lang` directory
4. Observe JavaScript files are not included in the file references.

### Screenshots, screen recording, code snippet

[NPM generated POT file](https://github.com/10up/distributor/files/9661010/distributor.pot.zip)

[WP CLI generated POT file](https://github.com/10up/distributor/files/9661020/distributor.pot.zip)

### Environment information

- Device: MacBook Pro (2020)
- Node version: v16.17.1

### WordPress information

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ravinderk**
### Description of the Change

 I create a bash script that uses `package.json --> files` to create a pot file for the addon. I implemented `EnqueueScript`, which manages script dependencies and versions based on the asset file generated by `@wordpress/dependency-extraction-webpack-plugin` package.
 
Closes #947 #267 #660

### How to test the Change

- Run `npm run makepot` command. It should generate a translation file that contains translations from a javascript file (only in `dist/js` directory). 
- Each script and style file should load correctly, which their versions and dependencies mentioned in the assets file.
- Each feature depends upon javascript and should work as expected.
- You should be able to edit translatable strings in Javascript or PHP files. You can use [Loco translate](https://wordpress.org/plugins/loco-translate/) plugin for testing.
  |  Action | Screenshot |
  |------------|--------|
  | Edit string | image image |
  | View edited string | Screenshot 2023-03-06 at 10 14 52 PM |
  | Translation files in plugin directory | image |

### Changelog Entry

> Added - Generate POT file with WP-CLI.
> Added - Register scripts with `EnqueueScript` class.

## Notable Changes
- Rename `./tests/php/bootstrap.php.dist --> ./tests/php/bootstrap.php` to get code editor support.

## Todo before release
- [ ] Ensure WP CLI exists in the built environment before generating the pot file. 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by ravinderk** [comment]
@peterwilsoncc E2E tests are passing locally but somehow falling on GitHub. Let me know if I am missing anything.

image

File: bin/generate-pot-with-wpcli.sh [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+# We are using wp-scripts to generate plugin zip which bundle files defined in 'package.json' in files param.
+# https://developer.wordpress.org/block-editor/packages/packages-scripts/#files
+# This script will run with npm run makepot command.
+#
+# @since x.x.x
+
+if ! command -v wp &>/dev/null; then
+	echo "Error: wp cli could not be found. Please install wp cli and try again."
+	exit
+fi
```
Comment (peterwilsoncc) [inline bin/generate-pot-with-wpcli.sh:13]: The pot files are built on the stable branch using a GitHub action.

https://github.com/10up/distributor/blob/a1a336a27da5027a62baf3abc1c7681ea1a11cc2/.github/workflows/build-stable.yml#L22-L23

You'll need to use the [setup-php action](https://github.com/shivammathur/setup-php#wrench-tools-support) we use in the tests file but specify that it include the wp cli as one of its tools. `wp i18n make-pot` doesn't use WordPress features so it doesn't need an actual WordPress install.

https://github.com/10up/distributor/blob/753c32541ebed15eddf1f9f56e7aae7cb732177d/.github/workflows/test.yml#L47-L52

File: includes/classes/EnqueueScript.php [hunk 2]
```diff
@@ -0,0 +1,284 @@
...
+			$script_asset['dependencies'],
+			$script_asset['version'],
+			$this->load_script_in_footer
+		);
+
+		if ( $this->register_translations ) {
+			wp_set_script_translations(
+				$this->script_id,
+				$this->text_domain,
+				$this->plugin_dir_path . 'languages'
```
Comment (peterwilsoncc) [inline includes/classes/EnqueueScript.php]:
```suggestion
				$this->plugin_dir_path . 'lang'
```

https://github.com/10up/distributor/blob/28c7cf2e9417898f0d7402e93b88d37d1ae00496/distributor.php#L14

File: includes/classes/EnqueueScript.php [hunk 3]
```diff
@@ -0,0 +1,284 @@
...
+	public function get_asset_file_data(): array {
+		$script_asset_path = trailingslashit( dirname( $this->absolute_script_path ) )
+			. basename( $this->absolute_script_path, '.js' )
+			. '.asset.php';
+
+		$script_asset = file_exists( $script_asset_path ) ?
+			require $script_asset_path :
+			[
+				'dependencies' => [],
+				'version'      => $this->version ?: filemtime( $this->absolute_script_path ), // phpcs:ignore
```
Comment (peterwilsoncc) [inline includes/classes/EnqueueScript.php]:
```suggestion
				'version'      => ! empty( $this->version ) ? $this->version : DT_VERSION,
```

On multi-server instances, the file time can vary between instances so best to fall back to the plugin version to improve cache hits. It will also be easier to get through [code review for VIP clients](https://docs.wpvip.com/technical-references/vip-platform/file-concatenation-and-minification/#h-versioning-to-bust-the-cache).

File: includes/classes/EnqueueScript.php [hunk 4]
```diff
@@ -0,0 +1,284 @@
...
+				$this->localize_script_param_name,
+				$this->localize_script_param_data
+			);
+		}
+
+		return $this;
+	}
+
+	/**
+	 * This function should be called before enqueue or register function.
```
Comment (peterwilsoncc) [inline includes/classes/EnqueueScript.php]:
```suggestion
	 * This function should be called before enqueue or register method.
```

File: includes/classes/EnqueueScript.php [hunk 5]
```diff
@@ -0,0 +1,284 @@
...
+	 * @since x.x.x
+	 */
+	public function register_translations(): EnqueueScript {
+		$this->register_translations = true;
+
+		return $this;
+	}
+
+	/**
+	 * This function should be called after enqueue or register function.
```
Comment (peterwilsoncc) [inline includes/classes/EnqueueScript.php]:
```suggestion
	 * This function should be called after enqueue or register method.
```

However, I am not sure the bit about enqueue is correct. WP places the content of `wp_localize_script()` before the script tag, so I think this will fail if called after enqueue.

File: includes/classes/EnqueueScript.php [hunk 6]
```diff
@@ -0,0 +1,284 @@
...
+ *
+ * @since x.x.x
+ */
+class EnqueueScript {
+	/**
+	 * Script ID.
+	 *
+	 * @since x.x.x
+	 */
+	private string $script_id;
```
Comment (peterwilsoncc) [inline includes/classes/EnqueueScript.php]:
```suggestion
	/**
	 * Script Handle.
	 *
	 * @since x.x.x
	 */
	private string $script_handle;
```

Let's call this `handle` to match the WP naming convention.

:1234: This will need to be renamed throughout.

File: includes/classes/EnqueueScript.php [hunk 7]
```diff
@@ -0,0 +1,284 @@
...
+	 * @since x.x.x
+	 *
+	 * @return array
+	 */
+	public function get_asset_file_data(): array {
+		$script_asset_path = trailingslashit( dirname( $this->absolute_script_path ) )
+			. basename( $this->absolute_script_path, '.js' )
+			. '.asset.php';
+
+		$script_asset = file_exists( $script_asset_path ) ?
```
Comment (peterwilsoncc) [inline includes/classes/EnqueueScript.php]: Ternary is difficult to read over multiple lines, let's just use a good old `if...else`.

File: includes/classes/EnqueueScript.php [hunk 8]
```diff
@@ -0,0 +1,284 @@
...
+	 * EnqueueScript constructor.
+	 *
+	 * @since x.x.x
+	 *
+	 * @param string $script_id   Script ID.
+	 * @param string $script_name Script name.
+	 *
+	 * @throws Exception If script file not found.
+	 */
+	public function __construct( string $script_id, string $script_name ) {
```
Comment (peterwilsoncc) [inline includes/classes/EnqueueScript.php]:
```suggestion
	 * @param string $script_id   Script ID.
	 * @param string $script_file_name Script name.
	 *
	 * @throws Exception If script file not found.
	 */
	public function __construct( string $script_id, string $script_fle_name ) {
```

Took me a moment to figure out this wasn't the handle.

File: includes/classes/EnqueueScript.php [hunk 9]
```diff
@@ -0,0 +1,284 @@
...
+		$this->plugin_dir_path      = DT_PLUGIN_PATH;
+		$this->plugin_dir_url       = trailingslashit( plugin_dir_url( DT_PLUGIN_FULL_FILE ) );
+		$this->text_domain          = 'distributor';
+		$this->script_id            = $script_id;
+		$this->relative_script_path = 'dist/js/' . $script_name . '.js';
+		$this->absolute_script_path = $this->plugin_dir_path . $this->relative_script_path;
+
+		if ( ! file_exists( $this->absolute_script_path ) ) {
+			throw new Exception( 'Script file not found: ' . $this->absolute_script_path );
```
Comment (peterwilsoncc) [inline includes/classes/EnqueueScript.php]: Without try/catches this will fatal so let's just trigger a notice instead.

File: assets/js/admin-external-connection.js [hunk 10]
```diff
@@ -6,6 +6,8 @@ import { addQueryArgs, isURL, prependHTTP } from '@wordpress/url';
 import { speak } from '@wordpress/a11y';
 import compareVersions from 'compare-versions';
 
+const { __, sprintf } = wp.i18n;
+
```
Comment (peterwilsoncc) [inline assets/js/admin-external-connection.js]:
```suggestion
import { speak } from '@wordpress/a11y';
import { __, sprintf } from '@wordpress/i18n';
import compareVersions from 'compare-versions';

```

:1234: Use `import` elsewhere in the PR too.

File: bin/generate-pot-with-wpcli.sh [hunk 11]
```diff
@@ -0,0 +1,22 @@
...
+
+# Get the list of files and directories which bundle in final zip file.
+FILES=$(node -p "require('./package.json').files.join(',')")
+
+# Run the WP-CLI command.
+# This command will generate a POT file in the root directory of the plugin and store it in land directory.
```
Comment (peterwilsoncc) [inline bin/generate-pot-with-wpcli.sh]:
```suggestion
# This command will generate a POT file in the root directory of the plugin and store it in lang directory.
```

File: bin/generate-pot-with-wpcli.sh [hunk 12]
```diff
@@ -0,0 +1,22 @@
...
+#
+# @since x.x.x
+
+if ! command -v wp &>/dev/null; then
+	echo "Error: wp cli could not be found. Please install wp cli and try again."
+	exit
+fi
+
+# Get the list of files and directories which bundle in final zip file.
+FILES=$(node -p "require('./package.json').files.join(',')")
```
Comment (peterwilsoncc) [inline bin/generate-pot-with-wpcli.sh]: This includes `"lang/**/*",` can this cause problems?

File: includes/distributed-post-ui.php [hunk 13]
```diff
@@ -127,16 +129,17 @@ function enqueue_post_scripts_styles( $hook ) {
...
+		array(),
+		$admin_distributed_post_script->get_script_id()
 	);
-	if ( file_exists( $asset_file ) ) {
-		$asset_data = require $asset_file;
-	}
 
-	wp_enqueue_style( 'dt-admin-distributed-post', plugins_url( '/dist/css/admin-distributed-post.min.css', __DIR__ ), array(), $asset_data['version'] );
-	wp_enqueue_script( 'dt-admin-distributed-post', plugins_url( '/dist/js/admin-distributed-post.min.js', __DIR__ ), $asset_data['dependencies'], $asset_data['version'], true );
+	$admin_distributed_post_script->load_in_footer()->enqueue();
```
Comment (peterwilsoncc) [inline includes/distributed-post-ui.php]: Can't do a suggestion because of GH things but can you move this to line 136 to group it with the `EnqueueScript` object?

File: includes/distributed-post-ui.php [hunk 14]
```diff
@@ -127,16 +129,17 @@ function enqueue_post_scripts_styles( $hook ) {
...
+	$admin_distributed_post_script = new EnqueueScript(
+		'dt-admin-distributed-post',
+		'admin-distributed-post.min'
+	);
+
+	wp_enqueue_style(
+		'dt-admin-distributed-post',
+		plugins_url( '/dist/css/admin-distributed-post.min.css', __DIR__ ),
+		array(),
+		$admin_distributed_post_script->get_script_id()
```
Comment (peterwilsoncc) [inline includes/distributed-post-ui.php]:
```suggestion
		$admin_distributed_post_script->get_version()
```

File: includes/syndicated-post-ui.php [hunk 15]
```diff
@@ -7,8 +7,12 @@
 
 namespace Distributor\SyndicatedPostUI;
 
+use Distributor\EnqueueScript;
 use Distributor\Utils;
 
+use function Distributor\Utils\distributable_post_statuses;
+use function Distributor\Utils\distributable_post_types;
+
```
Comment (peterwilsoncc) [inline includes/syndicated-post-ui.php]: I'd rather continue to use the `Utils\` notation here.

File: includes/syndicated-post-ui.php [hunk 16]
```diff
@@ -42,7 +46,7 @@ function() {
  * @since 1.0
  */
 function setup_columns() {
-	$post_types = \Distributor\Utils\distributable_post_types();
+	$post_types = distributable_post_types();
```
Comment (peterwilsoncc) [inline includes/syndicated-post-ui.php]: ... but am happy if you change this to `Utils\`

File: phpcs.xml [hunk 17]
```diff
@@ -19,4 +17,8 @@
 			</property>
 		</properties>
 	</rule>
+
+	<rule ref="Squiz.Commenting.VariableComment.MissingVar">
+		<severity>0</severity>
+	</rule>
```
Comment (peterwilsoncc) [inline phpcs.xml]: Why have you made this change?

**Review by peterwilsoncc — COMMENTED** [review]
I've added a few notes inline.

File: phpcs.xml (hunk 17 above)
Comment (ravinderk) [reply phpcs.xml]: @peterwilsoncc in PHP 7.4, you can define properties with their type. For this reason, it is not necessary to add `@var`.

File: includes/classes/EnqueueScript.php (hunk 9 above)
Comment (ravinderk) [reply includes/classes/EnqueueScript.php]: @peterwilsoncc this will throw a fatal error only if the file is missing. Please tell me in what scenario the file would be missing from the plugin.

File: phpcs.xml (hunk 17 above)
Comment (peterwilsoncc) [reply phpcs.xml]: Are you able to hold of on this so we can check for needs in the other classes too?

That way we can do a few things at once:
* see if we can enforce type declarations
* if so, remove this rule
* if so, enforce adding type declarations to properties

I'm not sure if the last one is possible yet but I only did a quick scan of the phpcs repo.

File: bin/generate-pot-with-wpcli.sh (hunk 12 above)
Comment (ravinderk) [reply bin/generate-pot-with-wpcli.sh]: @peterwilsoncc it will not cause an issue because WP CLI only sniffs javascript and  PHP files.

> Scans PHP, Blade-PHP and JavaScript files for translatable strings, as well as theme stylesheets and plugin files if the source directory is detected as either a plugin or theme.
ref: https://developer.wordpress.org/cli/commands/i18n/make-pot/


But I excluded `lang\` directory: https://github.com/10up/distributor/pull/1014/commits/40ee454bce484fbe49f2c54ecf87610ac375d83a

File: bin/generate-pot-with-wpcli.sh (hunk 1 above)
Comment (ravinderk) [reply bin/generate-pot-with-wpcli.sh:13]: @peterwilsoncc I updated `build-stable.yml`: https://github.com/10up/distributor/pull/1014/commits/d0709ab165a343d7a4d7785dfd8c9d31f361bece

Is there any way we can test this?

File: includes/classes/EnqueueScript.php (hunk 9 above)
Comment (peterwilsoncc) [reply includes/classes/EnqueueScript.php]: It should only happen if something goes wrong with the build action (it the webpack action it runs). In which case there's not much the site owner can do so best not to trigger a fatal error on their site. 

How about we compromise on:

```php
if ( defined( 'WP_DEBUG' ) && WP_DEBUG && ! file_exists() ) {
```

Comment (ravinderk) [reply includes/classes/EnqueueScript.php]: @peterwilsoncc I removed it, but we are responsible for ensuring the build is good.

File: bin/generate-pot-with-wpcli.sh (hunk 1 above)
Comment (peterwilsoncc) [reply bin/generate-pot-with-wpcli.sh:13]: > I updated `build-stable.yml`: [d0709ab](https://github.com/10up/distributor/commit/d0709ab165a343d7a4d7785dfd8c9d31f361bece)
> 
> Is there any way we can test this?

Not that I've been able to figure out...

@jeffpaul or @dkotter Have either of you got a surefire way of testing the build-stable workflow prior to running a release?

Comment (ravinderk) [reply bin/generate-pot-with-wpcli.sh:13]: @peterwilsoncc I think we can create a generate-zip action allowing us to test the final build without releasing it. Do we have an action to generate a zip?

Comment (ravinderk) [reply bin/generate-pot-with-wpcli.sh:13]: for example: https://github.com/10up/autoshare-for-twitter/blob/develop/.github/workflows/build-release-zip.yml

File: phpcs.xml (hunk 17 above)
Comment (ravinderk) [reply phpcs.xml]: @peterwilsoncc agree. I will revert those changes and use `@var`

Comment (ravinderk) [reply phpcs.xml]: ref: https://github.com/10up/distributor/pull/1014/commits/6f00cefd622731c087581b3ff21bbe1a2ea7e3b5

File: bin/generate-pot-with-wpcli.sh (hunk 1 above)
Comment (ravinderk) [reply bin/generate-pot-with-wpcli.sh:13]: I added a `Generate ZIP. GitHub workflow.

Comment (ravinderk) [reply bin/generate-pot-with-wpcli.sh:13]: you can experience generate zip action on https://github.com/ravinderk/distributor/actions/runs/4351571718

File: includes/bootstrap.php [hunk 18]
```diff
@@ -260,6 +205,7 @@ function() {
 			apply_filters( 'dt_network_site_connection_enabled', true )
 		) {
 			\Distributor\Connections::factory()->register( '\Distributor\InternalConnections\NetworkSiteConnection' );
+			load_plugin_textdomain( 'distributor', false, basename( dirname( DT_PLUGIN_FULL_FILE ) ) . '/lang' );
 		}
```
Comment (peterwilsoncc) [inline includes/bootstrap.php]:
```suggestion
		}
		load_plugin_textdomain( 'distributor', false, basename( dirname( DT_PLUGIN_FULL_FILE ) ) . '/lang' );
```

Ensures the translations load for sites using only external connections.

File: .github/workflows/generate-zip.yml [hunk 19]
```diff
@@ -0,0 +1,49 @@
+name: Generate ZIP
```
Comment (peterwilsoncc) [inline .github/workflows/generate-zip.yml:1]: LGTM.

I noticed it includes the files `.gitattributes` and `.github/workflows/*` unlike the built for release version but that may be one of two things:

* a bug introduced by, um, me
* needed for building the stable branch

Either way, not your problem.

**Comment by peterwilsoncc** [comment]
@ravinderk FYI, I've pushed in develop after merging #1022 -- I figured I'd do it as I knew it would create merge conflicts that would need to be resolved.

File: tests/php/EnqueueScriptTest.php [hunk 20]
```diff
@@ -0,0 +1,41 @@
+<?php
+
+namespace Distributor;
+
+use WP_Mock\Tools\TestCase;
+
+/**
+ * @since x.x.x
+ */
+class EnqueueScriptTest extends TestCase {
```
Comment (peterwilsoncc) [inline tests/php/EnqueueScriptTest.php:10]: Do you need any assistance with the tests? the mocks can make them a little complex.

File: .github/workflows/generate-zip.yml (hunk 19 above)
Comment (ravinderk) [reply .github/workflows/generate-zip.yml:1]: @peterwilsoncc These files were added because we intentionally included them: https://github.com/10up/distributor/blob/develop/package.json#L70

Can we remove them?

File: tests/php/EnqueueScriptTest.php (hunk 20 above)
Comment (ravinderk) [reply tests/php/EnqueueScriptTest.php:10]: @peterwilsoncc I added to update them later when I implement run tests on WordPress installation instead of mocks.

File: .github/workflows/generate-zip.yml (hunk 19 above)
Comment (peterwilsoncc) [reply .github/workflows/generate-zip.yml:1]: Let's keep them for now as it looks like they're needed for stable and the zip generation is mainly helpful for a test run.

**Review by peterwilsoncc — APPROVED** [review]
Thanks @ravinderk, this looks good to me.
