### PR TITLE
Ensure post abstraction methods use correct site ID.

### LINKED ISSUE #1007: Consider multisite for post abstraction.
### Describe the bug

Network connections make heavy use of the `switch_to_blog()` function. With regard to the post abstraction, this can be problematic if a helper method is called after switching blogs as the returned data can be a mix of content from the original site's post and the switched site's post.

For the methods within the post abstraction, it would be good to ensure the data always comes from the site used when the post abstraction was created.

### Steps to Reproduce

1. Create a fresh multisite install of WordPress (example below uses subdirectory mode)
2. Network activate distributor using the `develop` branch.
3. On the main site, edit the hello world's post's title to `Edited sample posts title`
4. Create a subsite (it should have the site ID 2)
5. Run the following in the wp cli shell command.
   ```
   wp> $dt_post = new Distributor\DistributorPost( 1 );
   wp> $dt_post->get_permalink();
   string "http://ms-distributor.local/?p=1"
   wp> $dt_post->post->post_title
   string "Edited sample posts title" 
   
   wp> switch_to_blog( 2 );
   wp> $dt_post->get_permalink();
   http://ms-distributor.local/two/?p=1
   wp> $dt_post->post->post_title
   string "Edited sample posts title"   
   ```

Note that after switching to site two, the `$dt_post` variable is returning a mix of data from the primary and secondary site

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by peterwilsoncc**
### Description of the Change

This resolves an issue in which the post abstraction can return a mix of data on Multisite networks when the site is switched.

It introduces the `DistributorPost::__call()` magic method to ensure the current site (`get_current_blog_id()`) matches the site ID used to instantiate the object.

To match the PHP behavior without the magic method, a fatal error is thrown if the method name does not exist.

To discourage developers from calling the helper methods while using a switched site, a notice is thrown if the magic method needs to switch sites.

To avoid site switching when possible, an in memory cache is used to bypass the site switch the second or subsequent time a method is called. The cached data is only used if the object is called from the wrong site to reduce the risk of errors caused by the addition/removal of hooks during runtime. Basically it's a performance compromise.

Closes #1007.
Supersedes #1004.

### TODO

* [x] Test interaction of magic methods: ensure `$dt_post->source_site` doesn't result in multiple switches

### Changelog Entry

> Fixed - Inconsistent data returned from post abstraction after site switch on multisite.

### Credits

Props @peterwilsoncc, @dkotter  

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: includes/classes/DistributorPost.php [hunk 1]
```diff
@@ -178,6 +186,74 @@ public function __construct( $post ) {
...
+			$switched = true;
+		}
+		$result = call_user_func_array( array( $this, $name ), $arguments );
+		if ( $switched ) {
+			restore_current_blog();
+		}
+		return $result;
+	}
+
+	/**
```
Comment (peterwilsoncc) [inline includes/classes/DistributorPost.php:279]: `::__get()` and `::__isset()` methods are unchanged but have been relocated to group all the magic methods together.

**Comment by peterwilsoncc** [comment]
In the revised PR #1010 (in draft), I went with a `__call` magic method to avoid statics. I'll see if I can use a cache to avoid switching sites when the method is used a second time.

**Comment by peterwilsoncc** [comment]
[Mini plugin I've been using for testing and checking error logs](https://github.com/10up/distributor/files/10564592/nope-call-magic-method.php.txt)

**Review by dkotter — APPROVED** [review]
