### PR TITLE
Check if the post is distributed, and if it is apply the author filter

### LINKED ISSUE #1015: Author override fails in the block theme author block.
### Describe the bug

Distributor offers a setting to replace the author of a post with a link to the original site.

The author details for a current post can be altered via a number of hooks

**Author display name**
* `the_author`
* `get_the_author_display_name`

**Author link**
* `author_link`
* `get_the_author_user_url`

In the hooks used by Distributor to filter the author details, they are only replaced if the functions were called without specifying a particular author. Without a particular author specified, WordPress returns the author of the current global post object.

https://github.com/10up/distributor/blob/753c32541ebed15eddf1f9f56e7aae7cb732177d/includes/hooks.php#L130-L137

https://github.com/10up/distributor/blob/753c32541ebed15eddf1f9f56e7aae7cb732177d/includes/hooks.php#L168-L175

In block themes, WordPress specified an author ID when rendering the author block, thereby causing the data not to be filtered by Distributor. ([Source code reference](https://github.com/WordPress/gutenberg/blob/a7415a80a95bdfee1f37261d5a286250d33e8117/packages/block-library/src/post-author-name/index.php#L21-L24))

### Steps to Reproduce

1. Create a network install of WordPress and activate Distributor
2. Distribute a post from one site to another
3. On the site the post was distributed to (ie the duplicate), activate Twenty Twenty, a classic theme.
4. Visit the distributed post, observe the author is replaced with the original site's details
5. On the site the post was distributed to (ie, the duplicate), activate Twenty Twenty Two, a block theme
6. Visit the distributed post, observe the author is not replaced with the original site's details

### Screenshots, screen recording, code snippet

Meta data for a distributed post with a block theme

Screen Shot 2023-02-10 at 1 17 20 pm

Meta data for a distributed post with a classic theme

Screen Shot 2023-02-10 at 1 17 59 pm

### Environment information

- PHP 7.4
- WordPress 6.1.1

### WordPress information

<details><summary>WordPress Information</summary>

### wp-core ###

version: 6.1.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: true
user_registration: false
blog_public: 1
default_comment_status: open
environment_type: local
site_count: 3
network_count: 1
user_count: 1
dotorg_communication: true

### wp-dropins (1) ###

db.php: true

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 2.1
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, custom-background, post-thumbnails, custom-logo, title-tag, html5, align-wide, responsive-embeds, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, editor-styles, widgets, menus, editor-style
theme_path: /vagrant/wp/wp-content/themes/twentytwenty

### wp-themes-inactive (12) ###

Twenty Eleven: version: 4.2, author: the WordPress team
Twenty Fifteen: version: 3.3, author: the WordPress team
Twenty Fourteen: version: 3.5, author: the WordPress team
Twenty Nineteen: version: 2.4, author: the WordPress team
Twenty Seventeen: version: 3.1, author: the WordPress team
Twenty Sixteen: version: 2.8, author: the WordPress team
Twenty Ten: version: 3.7, author: the WordPress team
Twenty Thirteen: version: 3.7, author: the WordPress team
Twenty Twelve: version: 3.8, author: the WordPress team
Twenty Twenty-One: version: 1.7, author: the WordPress team
Twenty Twenty-Three: version: 1.0, author: the WordPress team
Twenty Twenty-Two: version: 1.3, author: the WordPress team

### wp-mu-plugins (15) ###

custom-taxo.php: author: (undefined), version: (undefined)
Featured Image block bugfix for WP 6.0.3: author: (undefined), version: (undefined)
filter.php: author: (undefined), version: (undefined)
log-requests.php: author: (undefined), version: (undefined)
meta-data.php: author: (undefined), version: (undefined)
no-canon.php: author: (undefined), version: (undefined)
no-rest-for-the-wicked.php: author: (undefined), version: (undefined)
nope-call-magic-method.php: author: (undefined), version: (undefined)
nope-perf-test-multisite-stuff.php: author: (undefined), version: (undefined)
nope-post-abstraction-dumps.php: author: (undefined), version: (undefined)
plugin-api.php: author: (undefined), version: (undefined)
query-monitor-file-mappings.php: author: (undefined), version: (undefined)
switch-site-test.php: author: (undefined), version: (undefined)
unsafe-app-passwords.php: author: (undefined), version: (undefined)
wp-git-branch.php: author: (undefined), version: (undefined)

### wp-plugins-active (4) ###

Classic Editor: version: 1.6.2, author: WordPress Contributors
Distributor: version: 1.9.0, author: 10up Inc.
Query Monitor: version: 3.11.1, author: John Blackbourn
User Switching: version: 1.7.0, author: John Blackbourn & contributors

### wp-plugins-inactive (5) ###

Distributor - Edit Remote Post Meta: version: 0.2.1, author: 10up
Newspack Image Credits: version: 1.0.1, author: Automattic, INN Labs, Project Argo
Restricted Site Access: version: 7.3.5, author: Jake Goldman, 10up, Oomph
Test block: author: (undefined), version: (undefined)
Yoast SEO: version: 19.12, author: Team Yoast (latest version: 20.1)

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 1024M
upload_max_filesize: 1024M
max_effective_size: 1 GB
max_file_uploads: 20
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 5.15.0-30-generic x86_64
httpd_software: nginx/1.18.0
php_version: 7.4.30 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 900
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 900
upload_max_filesize: 1024M
php_post_max_size: 1024M
curl_version: 7.81.0 OpenSSL/3.0.2
suhosin: false
imagick_availability: false
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 8.0.30-0ubuntu0.22.04.1
client_version: mysqlnd 7.4.30
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: http://ms-distributor.local
WP_SITEURL: http://ms-distributor.local/wp
WP_CONTENT_DIR: /vagrant/content
WP_PLUGIN_DIR: /vagrant/content/plugins
WP_MEMORY_LIMIT: 64M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: local
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### distributor ###

0: 1.9.0
1: 
	Override Author Byline: Yes
	Media Handling: Featured image only
2: 
	10up Distributor Multisite: 
- Blog ID: 1
- URL: http://ms-distributor.local
- Registered: 2023-01-24 02:49:19
- Last updated: 2023-02-10 00:43:11
	MS Distributor Site Three: 
- Blog ID: 3
- URL: http://ms-distributor.local/three
- Registered: 2023-01-24 02:50:28
- Last updated: 2023-01-24 04:16:46
3: N/A

</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ggutenberg**
### Description of the Change

If an author ID is specified in a call to `get_the_author_meta()`, instead of returning the specified author blindly, we are also checking the post itself and whether or not it was distributed. If it was, we apply the `get_the_author_display_name` and `get_the_author_user_url` filters as usual.

Closes #1015 

### How to test the Change

Make sure you're using a theme that supports the block editor for this like Twenty Twenty-Two, as the Classic editor themes don't have an issue.

1. Create a post on the source site.
2. Distribute it to the target site.
3. In Distributor settings, make sure that `Override Author Byline` is checked.
4. View the distributed post on your site. Note that it displays the source site as the author.
5. Uncheck `Override Author Byline` in the Distributor settings.
6. View the distributed post on your site. Note that it now displays the target site's author.

### Changelog Entry

> Fixed - Author override fails in the block theme author block.

### Credits

Props @ggutenberg 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: includes/utils.php [hunk 1]
```diff
@@ -1182,3 +1182,14 @@ function remote_http_request( $url, $args = array(), $fallback = '', $threshold
...
 	return wp_remote_request( $url, $args );
 }
+
+/**
+ * Determines if a post is distributed.
+ *
+ * @param int $post_id The post ID.
+ * @return bool True if the post is distributed, false otherwise.
+ */
+function get_is_distributed_post( $post_id ) {
```
Comment (peterwilsoncc) [inline includes/utils.php]:
```suggestion
 * @param int|\WP_Post $post The post object or ID been checked.
 * @return bool True if the post is distributed, false otherwise.
 */
function is_distributed_post( $post ) {
	$post = get_post( $post );
	if ( ! $post ) {
		return false;
	}
	$post_id = $post->ID;
```

This does a couple of things:
* removes `get_` prefix, `is_` is a fairly common prefix in the plugin already
* accepts either a post object or ID, this is a common practice in core so I like to copy it

**Review by peterwilsoncc — COMMENTED** [review]
Tests well, thanks Garth.

I've made one suggestion inline.

File: includes/utils.php (hunk 1 above)
Comment (ggutenberg) [reply includes/utils.php]: Thanks @peterwilsoncc . Updated.

File: includes/utils.php [hunk 2]
```diff
@@ -1182,3 +1182,19 @@ function remote_http_request( $url, $args = array(), $fallback = '', $threshold
 
 	return wp_remote_request( $url, $args );
 }
+
+/**
+ * Determines if a post is distributed.
+ *
+ * @param int|\WP_Post $post The post object or ID been checked.
```
Comment (peterwilsoncc) [inline includes/utils.php:1191]:
```suggestion
 *
 * @since x.x.x
 *
 * @param int|\WP_Post $post The post object or ID been checked.
```

**Review by peterwilsoncc — APPROVED** [review]
LGMT, checked on a variety of block and classic themes.
