### PR TITLE
Limited external connection warning incorrect

### LINKED ISSUE #1071: Limited external connection warning incorrect
### Describe the bug

When setting up an external connection, manually configuring a connection with the incorrect username and password shows a warning:

> 🟡 Limited connection established.
> - Push distribution unavailable.
> - Pull distribution limited to basic content, i.e. title and content body.

However, since the migration to the custom end point for pulling content this error is incorrect as the custom endpoint requires users be logged in to pull content. 

The post type permissions list on the same screen shows the results correctly: no pushing or pulling is available.

### Steps to Reproduce

1. Go to the WP Dashboard > Distributor > External Connections > Add new
2. Click Manually Set Up Connection.
3. Enter an incorrect username and password combination
4. Enter a valid REST API endpoint in the URL field for a site that is running Distributor
5. The warning above will show
6. The push and pull permissions list will show no post types can be pushed or pulled
7. Save the connection
8. Visit Distributor > Pull Content
9. The new connection will not be listed as the site does not have any pullable content types
10. Publish a new post
11. Click "Distribute"
12. The new external connection will not be listed as the site does not have any pushable content types

### Screenshots, screen recording, code snippet

**Limited external connection showing incorrect warning**
Limited connection showing warning detailed above

**Pull Screen**
Pull screen, the limited external connection is not listed as an option

**Push screen**
Push screen, the limited external connection is not listed as an option

### Environment information

_No response_

### WordPress information

Running Development version of Distributor

<details><summary>Site Health Info</summary>

```
### wp-core ###

version: 6.2.3-alpha-55842
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /blog/%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: true
user_registration: false
blog_public: 1
default_comment_status: open
environment_type: local
site_count: 3
network_count: 1
user_count: 5
dotorg_communication: true

### wp-dropins (1) ###

db.php: true

### wp-active-theme ###

name: Twenty Twenty-Three (twentytwentythree)
version: 1.1
author: the WordPress team
author_website: https://wordpress.org
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, block-templates, widgets-block-editor
theme_path: /vagrant/wp-build/wp-content/themes/twentytwentythree

### wp-themes-inactive (12) ###

Twenty Eleven: version: 4.3, author: the WordPress team
Twenty Fifteen: version: 3.4, author: the WordPress team
Twenty Fourteen: version: 3.6, author: the WordPress team
Twenty Nineteen: version: 2.5, author: the WordPress team
Twenty Seventeen: version: 3.2, author: the WordPress team
Twenty Sixteen: version: 2.9, author: the WordPress team
Twenty Ten: version: 3.8, author: the WordPress team
Twenty Thirteen: version: 3.8, author: the WordPress team
Twenty Twelve: version: 3.9, author: the WordPress team
Twenty Twenty: version: 2.2, author: the WordPress team
Twenty Twenty-One: version: 1.8, author: the WordPress team
Twenty Twenty-Two: version: 1.4, author: the WordPress team

### wp-mu-plugins (6) ###

nope-post-abstraction-dumps.php: author: (undefined), version: (undefined)
nope-push-nope-pull.php: author: (undefined), version: (undefined)
query-monitor-file-mappings.php: author: (undefined), version: (undefined)
show-stable-dist.php: author: (undefined), version: (undefined)
snippet-auto-unlink.php: author: (undefined), version: (undefined)
unsafe-app-passwords.php: author: (undefined), version: (undefined)

### wp-plugins-active (3) ###

Distributor: version: 1.9.1, author: 10up Inc.
Query Monitor: version: 3.12.3, author: John Blackbourn
User Switching: version: 1.7.0, author: John Blackbourn & contributors

### wp-plugins-inactive (6) ###

Classic Editor: version: 1.6.3, author: WordPress Contributors
Distributor: version: 1.9.1, author: 10up Inc.
Distributor - Edit Remote Post Meta: version: 0.2.1, author: 10up
Newspack Image Credits: version: 1.0.1, author: Automattic, INN Labs, Project Argo
Test block: author: (undefined), version: (undefined)
Yoast SEO: version: 20.7, author: Team Yoast (latest version: 20.8)

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 1024M
upload_max_filesize: 1024M
max_effective_size: 1 GB
max_file_uploads: 20
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 5.15.0-30-generic x86_64
httpd_software: nginx/1.18.0
php_version: 7.4.33 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 900
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 900
upload_max_filesize: 1024M
php_post_max_size: 1024M
curl_version: 7.81.0 OpenSSL/3.0.2
suhosin: false
imagick_availability: false
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 8.0.30-0ubuntu0.22.04.1
client_version: mysqlnd 7.4.33
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: http://ms-distributor.local
WP_SITEURL: http://ms-distributor.local/wp
WP_CONTENT_DIR: /vagrant/content
WP_PLUGIN_DIR: /vagrant/content/plugins
WP_MEMORY_LIMIT: 64M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: local
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### distributor ###

0: 1.9.1
1: 
	Override Author Byline: Yes
	Media Handling: Featured image only
2: 
	10 Dist MS2: 
- Blog ID: 2
- URL: http://ms-distributor.local/two
- Registered: 2023-06-06 03:45:37
- Last updated: 2023-06-07 03:08:23
	10 Dist MS3: 
- Blog ID: 3
- URL: http://ms-distributor.local/three
- Registered: 2023-06-06 03:45:40
- Last updated: 2023-06-07 03:09:04
3: 

```

</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by theskinnyghost**
### Description of the Change
Closes #1071 

### How to test the Change

1. Go to the WP Dashboard > Distributor > External Connections > Add new
2. Click Manually Set Up Connection.
3. Enter an incorrect username and password combination
4. Enter a valid REST API endpoint in the URL field for a site that is running Distributor
5. Instead of the yellow warning, you should see a red error with a `Authentication failed due to insufficient or invalid credentials.` message instead
6. The push and pull permissions list will show no post types can be pushed or pulled
7. Save the connection
8. Visit Distributor > Pull Content
9. The new connection will not be listed as the site does not have any pullable content types
10. Publish a new post
11. Click "Distribute"
12. The new external connection will not be listed as the site does not have any pushable content types

### Changelog Entry

> Changed external connection status error messages when checking status

### Credits
Props @theskinnyghost 

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by theskinnyghost** [comment]
@peterwilsoncc I tried to run the cypress tests locally but wasn't able to so I'm not sure if I need to make any additional setup configuration to run them properly. Here's the error that I get when I run `npm run cypress:run` 
image

Also, is this the test I would need to update?
https://github.com/10up/distributor/blob/36d1c76/tests/cypress/e2e/external-connection.test.js#L99

File: assets/js/admin-external-connection.js [hunk 1]
```diff
@@ -348,6 +348,18 @@ function checkConnections() {
...
+
+				endpointResult.innerText = __(
+					'No connection found.',
+					'distributor'
+				);
+
+				speak(
+					__( 'No connection found.', 'distributor' ),
+					'polite'
+				);
```
Comment (peterwilsoncc) [inline assets/js/admin-external-connection.js]: Coding standards

```suggestion
				speak( __( 'No connection found.', 'distributor' ), 'polite' );
```

**Review by peterwilsoncc — COMMENTED** [review]
Thanks for the PR, Luca.

This is my fault but I the rest-api endpoint needs an update in the function `check_post_types_permissions()`, the permission check loop should be:

```php
foreach ( $types as $type ) {
	$caps = $type->cap;

	if ( current_user_can( $caps->edit_posts ) ) {
		$response['can_post'][] = $type->name;
	}

	if ( current_user_can( $caps->edit_posts ) && current_user_can( $caps->create_posts ) && current_user_can( $caps->publish_posts ) ) {
		$response['can_post'][] = $type->name;
	}
}
```

While testing, I noticed that if Distributor is not installed it shows the old limited connection message, as in this screenshot. This too will need to be updated to an error.

Screen Shot 2023-10-03 at 10 46 08 am


You're correct, the test you've linked to in `external-connection.test.js` is the one that needs an update. 

Getting Cypress running locally can be a little fiddly, were you able to get the environment running in Docker or did it fail before then?

**Comment by theskinnyghost** [comment]
Hey @peterwilsoncc, thanks for your feedback.

I made an update to show an error for the use case you mentioned above (when distributor is not installed).

I also updated the `check_post_types_permissions()` logic as per your suggestion but I'm not sure I did it right so I left a comment for you to check.

RE: Cypress Tests – I only ran `npm run cypress:run` and that's the error I got. Do I need to run additional commands? I use Local Flywheel not Docker.

File: includes/rest-api.php [hunk 2]
```diff
@@ -600,8 +600,11 @@ function check_post_types_permissions() {
 	);
 
 	foreach ( $types as $type ) {
-		$caps                  = $type->cap;
-		$response['can_get'][] = $type->name;
+		$caps = $type->cap;
+
+		if ( current_user_can( $caps->edit_posts ) ) {
+			$response['can_post'][] = $type->name;
```
Comment (theskinnyghost) [inline includes/rest-api.php]: @peterwilsoncc should this be `$response['can_get'][] = $type->name;` instead?

Comment (peterwilsoncc) [reply includes/rest-api.php]: > should this be `$response['can_get'][] = $type->name;` instead?

Yes, it should be. Sorry about that and thanks for picking up my silly moment.

Comment (theskinnyghost) [reply includes/rest-api.php]: Thank you and no worries. Updated! 😄

**Comment by peterwilsoncc** [comment]
> RE: Cypress Tests – I only ran `npm run cypress:run` and that's the error I got. Do I need to run additional commands? I use Local Flywheel not Docker.

The E2E tests use [`@wordpress/env`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/) which requires Docker. You may be able to change the URL returned by this function to use local but I've never had much luck doing that as a vagrant user.

https://github.com/10up/distributor/blob/0387c94509f4dbde5781628671b0b58abf5e3884/tests/cypress/config.js#L29-L48

I can take a look at the changes required.

File: assets/js/admin-external-connection.js [hunk 3]
```diff
@@ -314,7 +314,11 @@ function checkConnections() {
 		.done( ( response ) => {
 			if ( ! response.success ) {
 				endpointResult.setAttribute( 'data-endpoint-state', 'error' );
-			} else if ( response.data.errors.no_external_connection ) {
+			} else if (
+				response.data.errors.no_external_connection ||
+				'no' === response.data.is_authenticated ||
+				response.data.errors.no_distributor
```
Comment (peterwilsoncc) [inline assets/js/admin-external-connection.js]:
```suggestion
				response.data.errors.no_distributor ||
				! response.data.can_post.length
```

File: assets/js/admin-external-connection.js [hunk 4]
```diff
@@ -337,6 +341,18 @@ function checkConnections() {
...
+						'distributor'
+					);
+					speak(
+						__(
+							'Distributor not installed on remote site.',
+							'distributor'
+						),
+						'polite'
+					);
 				} else {
```
Comment (peterwilsoncc) [inline assets/js/admin-external-connection.js:372]: This is to make it a little clearer that the site has Distributor but the account has low or no permissions.

```suggestion
				} else if (
					'no' === response.data.is_authenticated ||
					response.data.errors.no_types
				) {
					endpointResult.innerText = __(
						'Authentication failed due to insufficient or invalid credentials.',
						'distributor'
					);
					speak(
						__(
							'Authentication failed due to insufficient or invalid credentials.',
							'distributor'
						),
						'polite'
					);
				} else {
```

File: tests/cypress/e2e/external-connection.test.js [hunk 5]
```diff
@@ -109,9 +109,9 @@ describe( 'Admin can add a new external connection', () => {
 		cy.get( '#dt_external_connection_url' ).type(
 			'http://localhost/second/wp-json'
 		);
-		cy.get( '.description.endpoint-result' ).should(
+		cy.get( '.endpoint-result' ).should(
 			'contain.text',
-			'Limited connection established.'
+			'No connection found'
```
Comment (peterwilsoncc) [inline tests/cypress/e2e/external-connection.test.js]:
```suggestion
			'Authentication failed due to insufficient or invalid credentials.'
```

**Review by peterwilsoncc — COMMENTED** [review]
I retested and was still seeing some unexpected warnings rather than errors, so have added a few more suggestions.

With these changes, I think we'll then be able to remove the `else if` beginning on [line 367](https://github.com/10up/distributor/blob/a7ec0387d89878ceff62c85d5aecedd31e9bb2e3/assets/js/admin-external-connection.js#L367-L411) -- it's outside the diff so I'm unable to include it as an inline suggestion.

**Comment by theskinnyghost** [comment]
@peterwilsoncc thanks again for your feedback. I implemented the changes you suggested but wasn't totally sure we could remove the `else if` from line 367 as that would completely remove warnings. Is that what you'd like to achieve here?

re: tests - I was able to run the tests this time by running `npm env:start` before running`npm run cypress:run`. However, a lot of tests are failing (even when I use the `develop` or `trunk` branch). I wonder if I'm missing anything here?

**Comment by peterwilsoncc** [comment]
> wasn't totally sure we could remove the `else if` from line 367 as that would completely remove warnings. Is that what you'd like to achieve here?

Yes, that's what I was after. The two conditions `response.data.errors.no_distributor || ! response.data.can_post.length` are both included in the first block now and throw errors instead of warnings.

A downside to switching to the dedicated Distributor endpoint is that it's basically all-or-nothing for connections at the moment. They'll either error or succeed, we're no longer able to have the partial connections that used to trigger warnings. 

As the block-editor becomes more important, the partial connections of old become less effective as the block editor requires access to the raw content.

> re: tests - I was able to run the tests this time by running `npm env:start` before running`npm run cypress:run`. However, a lot of tests are failing (even when I use the `develop` or `trunk` branch). I wonder if I'm missing anything here?

I'll test from scratch locally and reach out via the 10up Slack. It's possible the docs need to be updated.

**Comment by theskinnyghost** [comment]
Thanks @peterwilsoncc, I've updated the code and removed the warnings since they aren't applicable anymore. I also updated the tests and removed the test for warnings.
I also think we should add an additional test to make sure the `Distributor not installed on remote site.` error appears when that's the case but I'm not sure how to set this up with the current setup and also wanted to double check with you if that's needed.
I was able to run the tests just fine following the instructions you provided on 10up's Slack, thanks! 😄

**Comment by peterwilsoncc** [comment]
For others, these are the steps currently required to get the commands required to get e2e tests running locally.

Please ensure Docker is running before running these commands.

```
npm run env:destroy // Just to get back to scratch
npm run env:start
npm run copy-htaccess
npm run cypress:run
```

**Review by peterwilsoncc — APPROVED** [review]
Thanks Luca, this looks good to me.

Thanks for your patience during the review process, quite a bit had changed.
